version: "3.8"
services:
  pg_database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: subscriptions
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d subscriptions"]
      interval: 10s
      timeout: 5s
      retries: 10